version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: checksec-backend
    networks:
      - checksec-net
    environment:
      - MONGODB_URI=mongodb+srv://eyajrah6:admin123@cluster0.qmxbacx.mongodb.net/pfe?retryWrites=true&w=majority
      - SONAR_TOKEN=966a443fef12e0a5693a67534749669c8c7e994a
      - SONAR_ORGANIZATION=eyajrah
      - SONAR_PROJECT_KEY=eyajrah_checksec
      - SONAR_HOST_URL=https://sonarcloud.io
      - SONAR_SOURCES=.
      - SONAR_SOURCE_ENCODING=UTF-8
      - SNYK_TOKEN=614402cf-f16c-42d8-a704-b87794f02d8f
      - OWASP_DEPENDENCY_CHECK_PATH=/opt/dependency-check-8.3.1/bin/dependency-check.sh
      - NVD_API_KEY=d49ba8b5-40fc-427b-be47-7a695b1bb480
      - REPO_NAME=checksec
      - TEMP_DIR=/tmp/dependency-check
      - SUPPRESSION_FILE=/app/suppressions.xml
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /tmp/dependency-check:/tmp/dependency-check
    command: ["node", "server.js"]
  
  frontend:
    build:
      context: ./frontend
    container_name: checksec-front
    networks:
      - checksec-net
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: checksec-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mime.types:/etc/nginx/mime.types:ro
      - ./frontend/dist/temp-app/browser:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - checksec-net

networks:
  checksec-net:
    driver: bridge
