version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/monapp
    depends_on:
      - mongo

  frontend:
    build: 
      context: .  
      dockerfile: src/Dockerfile  
    ports:
      - "4200:80"
