name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Create sonar-project.properties
        run: |
          echo "sonar.projectKey=EyaJrah_pfe" > sonar-project.properties
          echo "sonar.organization=eyajrah" >> sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
          echo "sonar.sources=frontend/src,backend" >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          echo "sonar.exclusions=**/node_modules/**,**/*.spec.ts" >> sonar-project.properties

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
