name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=eyajrah_backend
            -Dsonar.organization=eyajrah
            -Dsonar.projectName=backend
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=backend
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
