name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Copy package files
        run: |
          cp frontend/package.json ./package.json
          cp frontend/package-lock.json ./package-lock.json 2>/dev/null || true

      - name: Install frontend dependencies
        run: |
          npm install
          mkdir -p frontend/node_modules
          mv node_modules/* frontend/node_modules/

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'CheckSec'
          path: '.'
          format: 'HTML JSON'
          args: >
            --enableExperimental
            --failOnCVSS 7
            --scan frontend/
            --scan backend/

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

      - name: Check for Critical Vulnerabilities
        run: |
          if grep -q '"severity": 9' reports/dependency-check-report.json || grep -q '"severity": 10' reports/dependency-check-report.json; then
            echo "Critical vulnerabilities found!"
            exit 1
          fi
