name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy package files
        run: |
          cp frontend/package.json ./package.json
          cp frontend/package-lock.json ./package-lock.json 2>/dev/null || true

      - name: Install frontend dependencies
        run: |
          npm install
          mkdir -p frontend/node_modules
          mv node_modules/* frontend/node_modules/

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        continue-on-error: true
        with:
          project: 'CheckSec'
          path: '.'
          format: 'HTML JSON'
          args: >
            --enableExperimental
            --failOnCVSS 9
            --scan frontend/
            --scan backend/
            --out reports

      - name: Debug Report Location
        if: always()
        run: |
          echo "Current directory contents:"
          ls -la
          echo "\nReports directory contents:"
          ls -la reports/ || echo "No reports directory found"
          echo "\nSearching for report files:"
          find . -type f -name "dependency-check-report.*"

      - name: Process Vulnerability Report
        if: always()
        run: |
          REPORT_FILE=$(find . -type f -name "dependency-check-report.json" | head -n 1)
          
          if [ -z "$REPORT_FILE" ]; then
            echo "ERROR: No report file found!"
            echo "Directory contents:"
            ls -la
            exit 1
          fi
          
          echo "Found report file at: $REPORT_FILE"
          echo "Report file contents:"
          cat "$REPORT_FILE" | head -n 20
          
          echo "### Dependency Check Results" > dependency-report.md
          echo "" >> dependency-report.md
          echo "#### High Severity Vulnerabilities (CVSS >= 9.0):" >> dependency-report.md
          
          if grep -q '"cvssv3_baseScore": [9,10]' "$REPORT_FILE"; then
            echo "⚠️ Critical vulnerabilities found!" >> dependency-report.md
            grep -B 2 -A 2 '"cvssv3_baseScore": [9,10]' "$REPORT_FILE" >> dependency-report.md
          else
            echo "✅ No critical vulnerabilities found." >> dependency-report.md
          fi
          
          echo "" >> dependency-report.md
          echo "#### Medium Severity Vulnerabilities (CVSS 7.0-8.9):" >> dependency-report.md
          grep -B 2 -A 2 '"cvssv3_baseScore": [7,8]' "$REPORT_FILE" >> dependency-report.md || true

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: |
            reports/dependency-check-report.*
            dependency-report.md
