name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install OWASP Dependency-Check CLI
        run: |
          VERSION="8.4.3"
          wget "https://github.com/jeremylong/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip"
          unzip dependency-check-${VERSION}-release.zip
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "PFE" \
            --scan . \
            --format HTML \
            --format JSON \
            --out reports \
            --failOnCVSS 7

      - name: Move reports to a dedicated directory
        if: always()
        run: |
          mkdir -p owasp-reports
          mv reports/* owasp-reports/ || true

      - name: Upload OWASP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: owasp-reports/
          retention-days: 30

      - name: Check for high vulnerabilities
        if: always()
        continue-on-error: true
        run: |
          if [ -f owasp-reports/dependency-check-report.json ]; then
            echo "Checking for high severity vulnerabilities..."
            HIGH_VULNS=$(jq '.dependencies[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.cvssv3_baseScore >= 7) | .name' owasp-reports/dependency-check-report.json | wc -l)
            if [ "$HIGH_VULNS" -gt 0 ]; then
              echo "⚠️ Found $HIGH_VULNS high severity vulnerabilities!"
              echo "Please check the generated report in the artifacts for details."
            else
              echo "✅ No high severity vulnerabilities found."
            fi
          else
            echo "⚠️ No JSON report found. Check HTML report for results."
          fi
