name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run OWASP Dependency Check using Docker
        run: |
          mkdir -p reports
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/reports:/report \
            owasp/dependency-check \
            --project "CheckSec" \
            --scan /src \
            --format HTML \
            --out /report \
            --failOnCVSS 7 \
            --enableRetired \
            --prettyPrint

      - name: Show Dependency Check logs
        run: cat reports/dependency-check-report.html || echo "No report found"

      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/
