name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Copy package files
        run: |
          cp frontend/package.json ./package.json
          cp frontend/package-lock.json ./package-lock.json 2>/dev/null || true

      - name: Install frontend dependencies
        run: |
          npm install
          mkdir -p frontend/node_modules
          mv node_modules/* frontend/node_modules/

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        continue-on-error: true
        with:
          project: 'CheckSec'
          path: '.'
          format: 'HTML JSON'
          args: >
            --enableExperimental
            --failOnCVSS 9
            --scan frontend/
            --scan backend/

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: reports/

      - name: Process Vulnerability Report
        if: always()
        run: |
          echo "### Dependency Check Results" > dependency-report.md
          echo "" >> dependency-report.md
          echo "#### High Severity Vulnerabilities (CVSS >= 9.0):" >> dependency-report.md
          if grep -q '"cvssv3_baseScore": [9,10]' reports/dependency-check-report.json; then
            echo "⚠️ Critical vulnerabilities found!" >> dependency-report.md
            grep -B 2 -A 2 '"cvssv3_baseScore": [9,10]' reports/dependency-check-report.json >> dependency-report.md
          else
            echo "✅ No critical vulnerabilities found." >> dependency-report.md
          fi
          
          echo "" >> dependency-report.md
          echo "#### Medium Severity Vulnerabilities (CVSS 7.0-8.9):" >> dependency-report.md
          grep -B 2 -A 2 '"cvssv3_baseScore": [7,8]' reports/dependency-check-report.json >> dependency-report.md

      - name: Upload Vulnerability Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: dependency-report.md
