name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Trivy vulnerability scanner for Frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './frontend'
          format: 'sarif'
          output: 'trivy-frontend-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          skip-dirs: 'frontend/node_modules'
          skip-files: 'frontend/package-lock.json'

      - name: Run Trivy vulnerability scanner for Backend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './backend'
          format: 'sarif'
          output: 'trivy-backend-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          skip-dirs: 'backend/node_modules'
          skip-files: 'backend/package-lock.json'

      - name: Upload Frontend Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: 'frontend-trivy'

      - name: Upload Backend Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: 'backend-trivy'

      - name: Generate Summary Reports
        run: |
          echo "# Security Scan Results" > trivy-summary.txt
          echo "## Frontend Vulnerabilities" >> trivy-summary.txt
          trivy filesystem --severity HIGH,CRITICAL ./frontend >> trivy-summary.txt
          echo "## Backend Vulnerabilities" >> trivy-summary.txt
          trivy filesystem --severity HIGH,CRITICAL ./backend >> trivy-summary.txt

      - name: Upload Summary Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-summary.txt
          retention-days: 7 