name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Trivy vulnerability scanner for Frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './frontend'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'library,vulnerability'
          output: 'trivy-frontend-results.txt'

      - name: Run Trivy vulnerability scanner for Backend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './backend'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'library,vulnerability'
          output: 'trivy-backend-results.txt'

      - name: Combine scan results
        run: |
          echo "=== Frontend Vulnerabilities ===" > trivy-combined-results.txt
          cat trivy-frontend-results.txt >> trivy-combined-results.txt
          echo -e "\n\n=== Backend Vulnerabilities ===" >> trivy-combined-results.txt
          cat trivy-backend-results.txt >> trivy-combined-results.txt

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-combined-results.txt
          retention-days: 7 