name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          scanners: 'vuln,secret,config,misconfig'
          hide-progress: false
          exit-code: '0'

      - name: Scan Docker configurations
        run: |
          echo "=== Docker Configuration Scan ===" > docker-scan.txt
          if [ -f frontend/Dockerfile ]; then
            echo "Frontend Dockerfile scan:" >> docker-scan.txt
            trivy config --severity CRITICAL,HIGH,MEDIUM,LOW frontend/Dockerfile >> docker-scan.txt
          fi
          if [ -f backend/Dockerfile ]; then
            echo "Backend Dockerfile scan:" >> docker-scan.txt
            trivy config --severity CRITICAL,HIGH,MEDIUM,LOW backend/Dockerfile >> docker-scan.txt
          fi

      - name: Scan npm dependencies
        run: |
          echo "=== NPM Dependencies Scan ===" > npm-scan.txt
          echo "Frontend dependencies:" >> npm-scan.txt
          cd frontend && trivy fs --scanners vuln --severity CRITICAL,HIGH,MEDIUM,LOW . >> ../npm-scan.txt || true
          echo "Backend dependencies:" >> npm-scan.txt
          cd ../backend && trivy fs --scanners vuln --severity CRITICAL,HIGH,MEDIUM,LOW . >> ../npm-scan.txt || true

      - name: Generate comprehensive report
        run: |
          {
            echo "# Security Scan Report"
            echo "## 1. File System Scan"
            trivy fs --scanners vuln,secret,config,misconfig --severity CRITICAL,HIGH,MEDIUM,LOW .
            echo -e "\n## 2. Docker Configuration Analysis"
            cat docker-scan.txt
            echo -e "\n## 3. Dependencies Analysis"
            cat npm-scan.txt
          } > trivy-results.txt

      - name: Display Trivy Results
        if: always()
        run: cat trivy-results.txt

      - name: Upload Trivy Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: |
            trivy-results.txt
            docker-scan.txt
            npm-scan.txt
          retention-days: 7 