name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Copy package files
        run: |
          cp frontend/package.json ./package.json
          cp frontend/package-lock.json ./package-lock.json 2>/dev/null || true

      - name: Install frontend dependencies
        run: |
          npm install
          mkdir -p frontend/node_modules
          mv node_modules/* frontend/node_modules/

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.txt'

      - name: List files after Trivy scan
        run: ls -l

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.txt
          retention-days: 7 